check50: 
    checks: 
        search: 
            - run: node main.js 
              stdout: | 
                  a
                  a-0->b
                  a-0->b-1->d
                  a-0->b-1->d-0->f
                  a-0->b-0->c
                  Solution  a-0->b-0->c-0->e
              exit: 0
