check50: 
    checks: 
        search: 
            - run: node puzzle.js 
              stdout: |
                Задание 0
                    А - лжец.
                Задание 1
                    А - лжец.
                    Б - рыцарь.
                Задание 2
                    А - лжец.
                    Б - рыцарь.
                Задание 3
                    А - рыцарь.
                    Б - лжец.
                    В - рыцарь.
              exit: 0
